# Copyright (c) 2023 Ferrous Systems
# Copyright (c) 2023 Jonathan 'theJPster' Pallant
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-code-analysis
run-name: Run code analysis
on: [push]
jobs:
  job-clippy-cmsim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check Clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: |
          cargo clippy --all-features
