# Copyright (c) 2023 Ferrous Systems
# Copyright (c) 2023 Jonathan 'theJPster' Pallant
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-code-format
run-name: Check code formatting
on: [push]
jobs:
  job-format-cmsim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check Formatting
        run: |
          cargo fmt -- --check
